apiVersion: apps/v1
kind: Deployment
metadata:
  name: app_name
  labels:
    app: app_name
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: app_name
  template:
    metadata:
      labels:
        app: app_name
      spce:
        containers:
          - name: app_name
            image: <account id>.dkr.ecr.<region>.amazonaws.com/<repo name>:latest
            ports:
              - containerPort: 80
                protocol: TCP
            imagePullPolicy: Always
            env:
              - name: ENV_VAR
                valueFrom:
                  secretKeyRef:
                    name: ecr-secret
                    key: ENV_VAR